name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ${{ secrets.CLOUDTYPE_PROJECT_NAME }}
          stage: main
          yaml: |
            name: fork-fork-fe
            app: node@20
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: API_BASE_URL
                  value: ${{ vars.API_BASE_URL }}
                - name: VITE_KAUTH_URL
                  value: ${{ vars.VITE_KAUTH_URL }}
                - name: VITE_KAKAO_SDK_KEY
                  value: ${{ secrets.VITE_KAKAO_SDK_KEY }}
                
              ports: 3000
              build: npm run build
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
